#!/usr/bin/env bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "Update system && install core packages"
if [[ $dry_run == "0" ]]; then
    # Verify that we are running not as root
    if [[ $EUID -eq 0 ]]; then
        echo "This script should not be run as root"
        exit 1
    fi

    if [[ -z "$HOME" ]]; then
        echo "HOME env var is not set"
        exit 1
    fi

    sudo apt update && sudo apt upgrade

    # Initial git setup
    git submodule init && git submodule sync
    git submodule update
    git config --global user.email "inom@iturdikulov.com"
    git config --global user.name "Inom Turdikulov"

    # Minimal install of most required packages
    sudo apt install -y yadm build-essential curl ca-certificates git

    if [ $? -ne 0 ]; then
      echo "Failed to update system, check logs above and try to fix all issues."
      exit 1
    fi
fi

log "RUN, grep: $grep"

runs_dir=`find $script_dir/runs -mindepth 1 -maxdepth 1 -executable`

for s in $runs_dir; do
    if echo "$s" | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi

    log "--- running script: $s ---"

    if [[ $dry_run == "0" ]]; then
        $s
    fi
done
