#!/usr/bin/env bash

# Source common utilities
source "$(dirname -- "${BASH_SOURCE[0]}")/runs/utils.sh"

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME" || exit 1

git config --global user.email "i@inomoz.ru"
git config --global user.name "Inom T."

yadm submodule update --recursive --init

echo "Now go to ~/.config/yadm/runs and execute required runners, e.g. 0_debian"
