#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd "$script_dir"

exec "$script_dir/run_runner.sh" --no-gui --blacklist "_hardware nvidia xone"
