#!/usr/bin/env bash

set -euo pipefail

# Increase wsl size
sudo mount -o remount,size=6G /tmp

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd "$script_dir"
# shellcheck source=runs/utils.sh
source "$script_dir/runs/utils.sh"

# Copy config if not exits
if ! [ -e /etc/wsl.conf ]; then
    sudo ln "$script_dir/wsl_conf/etc/wsl.conf" /etc/
    echo "WSL config linked successfully."
fi

if ! [ -e "/mnt/c/Users/inom/.wslconfig" ]; then
    cp "$script_dir/wsl_conf/.wslconfig" /mnt/c/Users/inom/.wslconfig
    echo "WSL config for win copied successfully."
fi

"$script_dir/run_runner.sh" --no-gui --no-ufw --blacklist "01_debian _hardware nvidia xone games gamedev _media _virt borg nginx resilio-sync singbox ttyd.sh whisper ollama_v2025"

"$script_dir/sync.sh"
