#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

VERSION=1.26.2

if command_exists go && go version >/dev/null 2>&1; then
    current_go_version="$(go version)"
    if [[ "$current_go_version" == *"go$VERSION "* ]]; then
        log_info "Go $VERSION is already installed; skipping reinstall."
        exit 0
    fi

    go clean -modcache
    go clean -cache
else
    log_warn "Skipping go cache cleanup; \`go version\` check failed."
fi

echo "Downloading GO"
wget2 --progress=bar --output-document /tmp/go_$VERSION.tar.gz "https://go.dev/dl/go$VERSION.linux-amd64.tar.gz"

echo "Installing GO"
sudo rm -rf /usr/bin/go && sudo tar -C /usr -xzf "/tmp/go_$VERSION.tar.gz"
rm "/tmp/go_$VERSION.tar.gz"

echo "set correct GOPATH and PATH in your shell!"
export GOPATH=$HOME/.local/go

cd /usr/local/go/bin/ || { echo "Failed"; exit 1; }
