#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

# Global Python
install_packages python3-full python3-aiohttp patchelf

# Get uv
if ! command -v uv &>/dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
else
    uv self update
fi

ensure_directory "$HOME/.local/bin"
cd "$HOME/.local/bin" || {
    echo "Error: Failed to change directory to $HOME/.local/bin" >&2
    exit 1
}

# Install tools
for tool in copier \
            ipython \
            pipdeptree \
            nuitka; do
    ./uv tool install --upgrade $tool
done
