#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

# Get cargo & rust toolchain
if ! command -v cargo &> /dev/null || ! command -v rustup &> /dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# Installing additional tools
export PATH="$PATH:$HOME/.cargo/bin"

# Cargo B(inary)Install
install_packages build-essential
cargo install cargo-binstall --locked

cargo install cargo-eval

rustup component add rust-src
