#!/usr/bin/env bash

# F3D and freecad
sudo apt install -y f3d freecad

# Blender
APP_RELEASE_TAG=alpha+main.f7c37b05e447
APP_VERSION=5.0.0
APP_NAME=blender
APP_DESKTOP_NAME=Blender
APP_DESKTOP_DESCRIPTION="Free and open-source 3D creation suite"
APP_DESKTOP_CATEGORIES="Graphics;Science"
APP_OUTPUT_NAME="blender-$APP_VERSION.tar.gz"

cd /tmp || { echo "cd failed"; exit 1; }
wget2 --progress=bar "https://cdn.builder.blender.org/download/daily/blender-$APP_VERSION-$APP_RELEASE_TAG-linux.x86_64-release.tar.xz" \
    --output-document $APP_OUTPUT_NAME
tar --extract --file $APP_OUTPUT_NAME -av -C ~/.local/
rm -f $APP_OUTPUT_NAME

mkdir -p "$HOME/.local/share/applications"
cat > "$HOME/.local/share/applications/$APP_NAME.desktop" << EOF
[Desktop Entry]
Version=$APP_VERSION
Name=$APP_DESKTOP_NAME
Comment=$APP_DESKTOP_DESCRIPTION
GenericName=$APP_DESKTOP_NAME
Exec=$HOME/.local/blender-$APP_VERSION-$APP_RELEASE_TAG-linux.x86_64-release/blender
Icon=$HOME/.local/bin/icons/$APP_NAME.svg
Terminal=false
Type=Application
Categories=$APP_DESKTOP_CATEGORIES
StartupNotify=true
EOF

# Find old version and suggest to remove
find "$HOME/.local/" -maxdepth 1 -type d -name "blender-*" ! -name "blender-$APP_VERSION*" -exec echo found old version, please remove manually {} +

