#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

for tool in llm \
	files-to-prompt; do
	uv tool install --upgrade $tool
done

uv tool run llm install \
	llm-openrouter \
	llm-ollama \
	llm-gemini \
	llm-mistral

# Agents
packages=(
    @openai/codex
	opencode-ai@latest
)

# Allow scripts to run for opencode-ai package
npm config set allow-scripts=opencode-ai --location=user

for package in "${packages[@]}"; do
    npm install -g "$package"
done

