#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

# Lazyjournal
curl -sSL https://github.com/Lifailon/lazyjournal/releases/download/0.8.6/lazyjournal-0.8.6-$(dpkg --print-architecture).deb -o /tmp/lazyjournal.deb
sudo apt install -y /tmp/lazyjournal.deb && rm /tmp/lazyjournal.deb

# Cursor + vscode repo

if [ ! -f /etc/apt/sources.list.d/cursor.sources ]; then
    CURSOR_VERSION=latest
    download_file "https://api2.cursor.sh/updates/download/golden/linux-x64-deb/cursor/$CURSOR_VERSION" /tmp/cursor.deb
    sudo dpkg -i /tmp/cursor.deb && rm /tmp/cursor.deb
fi

install_packages code cursor

# Sandbox tools for codex
install_packages seccomp bubblewrap

packages=(
    @openai/codex
    @google/gemini-cli
    @zed-industries/codex-acp
)

for package in "${packages[@]}"; do
    npm install -g "$package"
done
