#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install git lazygit ripgrep fd-find zoxide jq tealdeer shutter python3-pip 7zip btrbk wl-clipboard wget2
sudo apt -y install htop libsensors5 ncdu apt-show-versions detox

tldr --update
