#!/usr/bin/env bash

sudo apt remove vlc dragonplayer
sudo apt install -y mpv obs-studio audacity kdenlive lmms ffmpeg cmus ani-cli picard
sudo apt install -y krita inkscape imagemagick darktable qrencode gimp mypaint-brushes

wget2 --progress=bar --output-document ~/.local/bin/yt-dlp \
    "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux"
chmod +x ~/.local/bin/yt-dlp

wget2 --progress=bar --output-document ~/.local/bin/lossless-cut \
    "https://github.com/mifi/lossless-cut/releases/latest/download/LosslessCut-linux-x86_64.AppImage"
chmod +x ~/.local/bin/lossless-cut

# LAUNCHER
APP="no.mifi.losslesscut.desktop"
mkdir -p "$HOME/.local/share/applications"
echo "[Desktop Entry]
Name=LosslessCut
Comment=simple video editor to trim or cut videos
Comment[fr]=Un simple éditeur vidéo pour retailler ou couper les vidéos
Exec=$HOME/.local/bin/lossless-cut
MimeType=video/mpeg;video/x-mpeg;video/msvideo;video/quicktime;video/x-anim;video/x-avi;video/x-ms-asf;video/x-ms-wmv;video/x-msvideo;video/x-nsv;video/x-flc;video/x-fli;video/x-flv;video/vnd.rn-realvideo;video/mp4;video/mp4v-es;video/mp2t;application/ogg;application/x-ogg;video/x-ogm+ogg;audio/x-vorbis+ogg;application/x-matroska;audio/x-matroska;video/x-matroska;video/webm;
Icon=$HOME/.local/bin/icons/losslesscut.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=AudioVideo;AudioVideoEditing;
Keywords=trim;codec;cut;movie;mpeg;avi;h264;mkv;mp4;
StartupWMClass=losslesscut" > "$HOME/.local/share/applications/$APP.desktop"
