#!/usr/bin/env bash

sudo apt remove firewalld kmail akregator kaddressbook
sudo apt install -y aria2 wget2 curl thunderbird rsync nfs-common kdeconnect sshfs openssh-server autossh

# KDE automount script
cat > "$HOME/.config/autostart/kde_connect.desktop" << EOF
[Desktop Entry]
Exec=$HOME/.local/scripts/kde_connect.sh
Icon=dialog-scripts
Name=kde_connect.sh
Terminal=false
X-MultipleArgs=false
Type=Application
EOF

# WARN: Enable firewall for debian!
sudo apt install -y ufw
sudo systemctl enable ufw.service
sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow ssh
sudo ufw allow nfs

# KDE connect rules
sudo ufw allow 1716:1764/tcp
sudo ufw allow 1716:1764/udp

# Custom
sudo ufw allow 8080/tcp
sudo ufw allow 9090/tcp

sudo ufw enable
sudo ufw status verbose

for share in anime movie shows software
do
    # Add nfs share mount entry
    if ! grep -q "kama:/$share" /etc/fstab ; then
        echo "Mounting $share share"
        mkdir -p "$HOME/Media/$share"
        echo "kama:/$share $HOME/Media/$share nfs noauto,nofail,noatime,nfsvers=4.2,x-systemd.automount,x-systemd.idle-timeout=120,x-gvfs-trash 0 0" | \
    	    sudo tee --append /etc/fstab
        sudo mount "$HOME/Media/$share"
    fi
done

sudo systemctl daemon-reload
