#!/usr/bin/env bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Installing additional tools
cd $HOME/.cargo/bin

./cargo install stylua --features luajit
./cargo install atuin

if [ -n "$(lspci|grep VGA|grep -i 'AMD\|ATI')" ]; then
    if [ ! -n "$(lspci|grep VGA|grep AMD)" ]; then
        # Install radeontop if an AMD card is present
    fi
fi
