#!/usr/bin/env bash

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/utils.sh"

# Base dependencies
install_packages nasm

# Get cargo & rust toolchain
if ! command -v cargo &> /dev/null || ! command -v rustup &> /dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# Installing additional tools
export PATH="$PATH:$HOME/.cargo/bin"

cargo install atuin \
tun2proxy \
asm-lsp \
cargo-eval \
git-delta \
leetcode-cli \
tex-fmt

cargo install stylua --features luajit
cargo install --locked --git https://github.com/Feel-ix-343/markdown-oxide.git markdown-oxide
cargo install --locked --git https://github.com/j178/prek

cargo install mago && mago self-update

rustup component add rust-analyzer
rustup component add rust-src

if lspci | grep VGA | grep -q AMD; then
    log_info "Installing amdgpu_top"
    install_packages libdrm-dev
    cargo install amdgpu_top
fi
