#!/usr/bin/env bash

# Base dependencies
sudo apt install -y nasm

# Get cargo & rust toolchain
if ! command -v cargo &> /dev/null || ! command -v rustup &> /dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

# Installing additional tools
cd "$HOME/.cargo/bin" || { echo "cd failed"; exit 1; }

./cargo install atuin
./cargo install tun2proxy

./cargo install stylua --features luajit
./cargo install asm-lsp
./cargo install cargo-eval
./cargo install git-delta
./cargo install leetcode-cli
./cargo install tex-fmt
./cargo install --locked --git https://github.com/Feel-ix-343/markdown-oxide.git markdown-oxide
./cargo install --locked --git https://github.com/j178/prek
./cargo install mago && mago self-update

./rustup component add rust-analyzer
./rustup component add rust-src

if lspci | grep VGA | grep -q AMD; then
    echo "Installing amdgpu_top"
    sudo apt install -y libdrm-dev
    ./cargo install amdgpu_top
fi
