#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

install_packages qemu-system libvirt-daemon-system virtiofsd
sudo adduser `id -un` libvirt
sudo virsh net-autostart default
sudo virsh net-start default
