#!/usr/bin/env bash

git clone https://github.com/iturdikulov/slimzsh "$HOME/.config/slimzsh"
cd "$HOME/.config/slimzsh" || exit 1
git submodule update --init --recursive

sudo apt install -y zsh direnv glow cloc zsh-autosuggestions
sudo chsh -s $(which zsh)
sudo chsh -s $(which zsh) $(whoami)

# Fix insecure directories
sudo chmod 755 "$HOME/.config/"
sudo chmod 755 "$HOME/.config/slimzsh"
sudo chmod 755 "$HOME/.config/slimzsh/fast-syntax-highlighting/"

# Prompt
sudo apt install -y starship
