#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

sudo apt install libxcb-xinerama0 libxcb-cursor0 iptables
cd "/tmp" || exit 1
wget2 --progress=bar --output-document amnezia.tar.zip https://github.com/amnezia-vpn/amnezia-client/releases/download/4.8.11.4/AmneziaVPN_4.8.11.4_linux_x64.tar.zip
tar zxf amnezia.tar.zip
sudo ./AmneziaVPN_Linux_Installer.bin && rm -f AmneziaVPN_Linux_Installer.bin
