#!/bin/sh

curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && \
    chmod +x copilot && \
    mv copilot "$HOME/.local/bin/copilot" && "$HOME/.local/bin/copilot" --help

cd "/tmp" && \
curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb" && \
    sudo dpkg -i session-manager-plugin.deb && \
    rm -f session-manager-plugin.deb


