#!/usr/bin/env bash

BASE_VERSION=4.4
VERSION="$BASE_VERSION".1

wget2 -O /tmp/blender.tar.xz "https://ftp.nluug.nl/pub/graphics/blender/release/Blender$BASE_VERSION/blender-$VERSION-linux-x64.tar.xz"
mkdir -p ~/.local/share/applications
cat > $HOME/.local/share/applications/Blender.desktop << EOF
[Desktop Entry]
Version=$VERSION
Name=Blender
Comment=Blender
GenericName=Blender
Exec=$HOME/.local/blender-$VERSION-linux-x64/blender
Terminal=false
Type=Application
Icon=$HOME/.local/blender-$VERSION-linux-x64/blender.svg
Categories=GTK;Graphics
MimeType=application/x-blender;
StartupNotify=true
EOF
tar -xJf /tmp/blender.tar.xz -C ~/.local

