#!/usr/bin/env bash

PKGURL="https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb"
cd /tmp
wget -O dbeaver-ce_latest_amd64.deb $PKGURL
sudo apt install ./dbeaver-ce_latest_amd64.deb
rm ./dbeaver-ce_latest_amd64.deb
