#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

if ! command_exists "devpod"
then
    cd /tmp || exit 1
    curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64" && sudo install -c -m 0755 devpod /usr/local/bin && rm -f devpod
fi

# To get list of providers run
# devpod provider list-available
devpod provider add docker
devpod provider add ssh



