#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

sudo apt-get install --no-install-recommends -y ca-certificates
EDGE_VERSION=$(curl -sL https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/ |
    awk -F'(<a href="microsoft-edge-stable_|_amd64.deb\")' '/href=/ {print $2}' | sort --version-sort | tail -1)
curl -o /tmp/edge.deb -L "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_${EDGE_VERSION}_amd64.deb"
sudo dpkg -I /tmp/edge.deb
sudo apt install --no-install-recommends -y /tmp/edge.deb && rm /tmp/edge.deb

mkdir -p "$HOME/.local/share/applications"
rm -f "$HOME/.local/share/applications/microsoft-edge.desktop"
cat > "$HOME/.local/share/applications/com.microsoft.Edge.desktop" << EOF
[Desktop Entry]
Version=1.0
Name=Microsoft Edge
GenericName=Web Browser
Comment=Access the Internet
Exec=/home/inom/.local/bin/microsoft-edge %U
Icon=microsoft-edge
Terminal=false
Type=Application
Categories=Network;WebBrowser;
MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/microsoft-edge;x-scheme-handler/chromium;
NoDisplay=false
StartupNotify=true
Actions=new-window;new-private-window;

[Desktop Action new-window]
Name=New Window
Exec=/usr/bin/microsoft-edge-stable

[Desktop Action new-private-window]
Name=New InPrivate Window
Exec=/usr/bin/microsoft-edge-stable --inprivate
EOF

update-desktop-database "$HOME/.local/share/applications/"
