#!/usr/bin/env bash

sudo apt-get install --no-install-recommends -y ca-certificates
EDGE_VERSION=$(curl -sL https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/ |
    awk -F'(<a href="microsoft-edge-stable_|_amd64.deb\")' '/href=/ {print $2}' | sort --version-sort | tail -1)
curl -o /tmp/edge.deb -L "https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_${EDGE_VERSION}_amd64.deb"
sudo dpkg -I /tmp/edge.deb
sudo apt install --no-install-recommends -y /tmp/edge.deb && rm /tmp/edge.deb
