#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

sudo apt install -y fonts-firacode fonts-terminus

# Download Terminus Nerd Font (tar.xz)
OUTPUT_FILE=/tmp/terminus.tar.xz

! [ -f "$OUTPUT_FILE" ] && wget2 -O $OUTPUT_FILE "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/Terminus.tar.xz" \
|| echo "$OUTPUT_FILE already exist, skip downloading"

# Terminus
#
# Verify
SHA_SUM=$(sha256sum "$OUTPUT_FILE")
echo "e857b18a99701528f873275b6012792caf6e30c34c512ee92cda51520140054f" "$OUTPUT_FILE" | sha256sum -c || { echo "Invalid sha $SHA_SUM for $OUTPUT_FILE, skip installing font"; exit 1; }

# Create font directory
mkdir -p "$HOME/.local/share/fonts/Terminus"
tar -xf /tmp/terminus.tar.xz -C "$HOME/.local/share/fonts/Terminus" && rm "$OUTPUT_FILE"
fc-cache -fv
echo "Terminus Nerd Font installed."

# Commit Mono
#
# Download Commit Mono Font (tar.xz)
OUTPUT_FILE=/tmp/commit_mono.tar.xz

# Verify
! [ -f "$OUTPUT_FILE" ] && wget2 -O $OUTPUT_FILE "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/CommitMono.tar.xz" \
|| echo "$OUTPUT_FILE already exist, skip downloading"
SHA_SUM=$(sha256sum "$OUTPUT_FILE")
echo "44cdabae7708de3548fdd78ed59cdbb1fedbca18e16644047ed4a23623a530ca" "$OUTPUT_FILE" | sha256sum -c || { echo "Invalid sha $SHA_SUM for $OUTPUT_FILE, skip installing font"; exit 1; }

# Create font directory
mkdir -p "$HOME/.local/share/fonts/CommitMono"
tar -xf /tmp/commit_mono.tar.xz -C "$HOME/.local/share/fonts/CommitMono" && rm "$OUTPUT_FILE"
fc-cache -fv
echo "Commit Mono Font installed."

# Iosevka
# Download Iosevka Nerd Font (tar.xz)
OUTPUT_FILE=/tmp/iosevka.tar.xz

! [ -f "$OUTPUT_FILE" ] && wget2 -O $OUTPUT_FILE "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/IosevkaTerm.tar.xz" \
|| echo "$OUTPUT_FILE already exist, skip downloading"

# Verify
SHA_SUM=$(sha256sum "$OUTPUT_FILE")
echo "cad9da572d25e3413f7a15a319d2f3c9e7e915ee016baa99e0d88fc08cf5b781" "$OUTPUT_FILE" | sha256sum -c || { echo "Invalid sha $SHA_SUM for $OUTPUT_FILE, skip installing font"; exit 1; }

# Create font directory
mkdir -p "$HOME/.local/share/fonts/Iosevka"
tar -xf /tmp/iosevka.tar.xz -C "$HOME/.local/share/fonts/Iosevka" && rm "$OUTPUT_FILE"
fc-cache -fv
echo "Iosevka Nerd Font installed."
