#!/usr/bin/env bash

sudo apt install -y foot

 
APP_NAME=foot_ext
APP_DESKTOP_NAME=foot_ext

mkdir -p $HOME/.local/share/applications
cat > "$HOME/.local/share/applications/$APP_NAME.desktop" << EOF
[Desktop Entry]
Version=$APP_VERSION
Name=$APP_DESKTOP_NAME
GenericName=$APP_DESKTOP_NAME
Exec=foot --title foot_ext --app-id=foot_ext --maximized --override colors.background=29243B
Icon=$HOME/.local/bin/icons/$APP_NAME.svg
Terminal=false
Type=Application
Categories=Utility
StartupNotify=true
EOF
