#!/usr/bin/env bash

set -u

APP_VERSION=1.0.0

APP_NAME=freecad
APP_DESKTOP_NAME=FreeCAD
APP_DESKTOP_DESCRIPTION="Feature based parametric 3D CAD modeler"
APP_DESKTOP_CATEGORIES="Graphics;Science"

APP_PATH="$HOME/.local/bin/$APP_NAME"
TMP_PATH="/tmp/$APP_NAME"
APP_URL="https://github.com/FreeCAD/FreeCAD/releases/download/$APP_VERSION/FreeCAD_$APP_VERSION-conda-Linux-x86_64-py311.AppImage"
SHA_256_SUM="4b1c53e7f444a7897875064e059be84c0ebb8848dd58bc034dcdd1ccc407dbc7"

wget2 --progress=bar --output-document $TMP_PATH $APP_URL
echo "$SHA_256_SUM $TMP_PATH" | sha256sum --check || exit 1

mv $TMP_PATH $APP_PATH
chmod a+x $APP_PATH

mkdir -p $HOME/.local/share/applications
cat > "$HOME/.local/share/applications/$APP_NAME.desktop" << EOF
[Desktop Entry]
Version=$APP_VERSION
Name=$APP_DESKTOP_NAME
Comment=$APP_DESKTOP_DESCRIPTION
GenericName=$APP_DESKTOP_NAME
Exec=$HOME/.local/bin/$APP_NAME
Icon=$HOME/.local/bin/icons/$APP_NAME.svg
Terminal=false
Type=Application
Categories=$APP_DESKTOP_CATEGORIES
StartupNotify=true
EOF
