#!/usr/bin/env bash

sudo apt remove fzf

# Create temp directory for the build
TEMP_DIR=$(mktemp -dt "$(basename $0).XXXXXX")
cd $TEMP_DIR

curl -s -L https://github.com/junegunn/fzf/releases/download/v0.61.1/fzf-0.61.1-linux_amd64.tar.gz --output fzf.tar.gz

# Extract contents of archive
tar -xvf fzf.tar.gz

# Copy binary to bin directory
cp fzf $HOME/.local/bin
