#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

sudo dpkg --add-architecture i386

install_packages mesa-vulkan-drivers libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386

# protontricks to tune proton prefixes and protontricks-launch to launch games
# gamemode to tune hardware while playing games
install_packages winetricks gamemode gamescope vkbasalt
sudo usermod -aG gamemode $USER
