#!/usr/bin/env bash

sudo dpkg --add-architecture i386
sudo apt update

sudo apt -y install steam-installer icoutils
sudo apt -y install mesa-vulkan-drivers libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386

# protontricks to tune proton prefixes and protontricks-launch to launch games
# gamemode to tune hardware while playing games
sudo apt -y install winetricks gamemode gamescope lutris antimicro
sudo usermod -aG gamemode $USER

# protonup-qt
URL="https://github.com/DavidoTek/ProtonUp-Qt/releases/download/v2.12.0/ProtonUp-Qt-2.12.0-x86_64.AppImage"
wget2 --progress=bar --output-document $HOME/.local/bin/ProtonUp-Qt.AppImage $URL
chmod a+x $HOME/.local/bin/ProtonUp-Qt.AppImage

mkdir -p $HOME/.local/share/applications
cat > $HOME/.local/share/applications/ProtonUp-Qt.desktop << EOF
[Desktop Entry]
Version=2.12.0
Name=ProtonUp-Qt
Comment=Install and manage Proton-GE and Luxtorpeda for Steam and Wine-GE for Lutris
GenericName=ProtonUp-Qt
Exec=$HOME/.local/bin/ProtonUp-Qt.AppImage
Icon=games-config-options
Terminal=false
Type=Application
Categories=GTK;Game
StartupNotify=true
EOF
