#!/usr/bin/env bash

sudo apt install -y libsdl2-dev

# TODO: parametrize!

mkdir -p ~/.local/bin
cd ~/.local/bin

APP=Godot_v4.4.1-stable_linux.x86_64
URL=https://github.com/godotengine/godot/releases/download/4.4.1-stable/$APP.zip

wget2 "$URL" || exit 1
[ -e ./*7z ] && 7z x ./*7z && rm -f ./*7z
[ -e ./*tar.* ] && tar fx ./*tar.* && rm -f ./*tar.*
[ -e ./*zip ] && unzip -qq ./*zip 1>/dev/null && rm -f ./*zip
chmod a+x ./$APP || exit 1
mv ./$APP godot

# LAUNCHER
echo "[Desktop Entry]
Name=Godot Engine
GenericName=Libre game engine
GenericName[el]=Ελεύθερη μηχανή παιχνιδιού
GenericName[fr]=Moteur de jeu libre
GenericName[nl]=Libre game-engine
GenericName[zh_CN]=自由的游戏引擎
Comment=Multi-platform 2D and 3D game engine with a feature-rich editor
Comment[el]=2D και 3D μηχανή παιχνιδιού πολλαπλών πλατφορμών με επεξεργαστή πλούσιο σε χαρακτηριστικά
Comment[fr]=Moteur de jeu 2D et 3D multiplateforme avec un éditeur riche en fonctionnalités
Comment[nl]=Multi-platform 2D- en 3d-game-engine met een veelzijdige editor
Comment[zh_CN]=多平台 2D 和 3D 游戏引擎，带有功能丰富的编辑器
Exec=$HOME/.local/bin/godot %f
Icon=$HOME/.local/bin/icons/godot.svg
Terminal=false
PrefersNonDefaultGPU=true
Type=Application
MimeType=application/x-godot-project;
Categories=Development;IDE;
StartupWMClass=Godot" > $HOME/.local/share/applications/"$APP".desktop
