#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
chmod 755 "$TMP_DIR"

download_file \
    "https://github.com/dariogriffo/ghostty-debian/releases/download/1.3.1%2B3/ghostty-dbgsym_1.3.1-3+trixie_amd64.deb" \
    "$TMP_DIR/ghostty-dbgsym_1.3.1-3+trixie_amd64.deb"
download_file \
    "https://github.com/dariogriffo/ghostty-debian/releases/download/1.3.1%2B3/ghostty_1.3.1-3+trixie_amd64.deb" \
    "$TMP_DIR/ghostty_1.3.1-3+trixie_amd64.deb"
chmod a+r \
    "$TMP_DIR/ghostty-dbgsym_1.3.1-3+trixie_amd64.deb" \
    "$TMP_DIR/ghostty_1.3.1-3+trixie_amd64.deb"

sudo apt install -y -f \
    "$TMP_DIR/ghostty-dbgsym_1.3.1-3+trixie_amd64.deb" \
    "$TMP_DIR/ghostty_1.3.1-3+trixie_amd64.deb"
