#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

ARCH="$(dpkg --print-architecture)"
curl -LO https://download.opensuse.org/repositories/home:/clayrisser:/sid/Debian_Unstable/$ARCH/ghostty_1.1.3-4_$ARCH.deb
sudo apt install ./ghostty_1.1.3-4_$ARCH.deb

# Custom ghostty destkop file
mkdir -p $HOME/.local/share/applications
cat > $HOME/.local/share/applications/ghostty-main.desktop << EOF
[Desktop Entry]
Version=1.0
Name=az
GenericName=Terminal Emulator
Comment=Ghostty instance with custom class main.app
Exec=ghostty -e az
Terminal=false
Type=Application
Icon=utilities-terminal
Categories=System;TerminalEmulator;
StartupWMClass=main.app
Keywords=shell;prompt;command;commandline;
StartupNotify=true
EOF
update-desktop-database ~/.local/share/applications/
