#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

VERSION=1.24.2
echo "Downloading GO"
wget2 --progress=bar --output-document /tmp/go_$VERSION.tar.gz "https://go.dev/dl/go$VERSION.linux-amd64.tar.gz"

echo "Installing GO"
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf "/tmp/go_$VERSION.tar.gz"
rm "/tmp/go_$VERSION.tar.gz"

echo "set correct GOPATH and PATH in your shell!"
export GOPATH=$HOME/.local/go

cd /usr/local/go/bin/ || { echo "Failed"; exit 1; }

# Install gopls lang server
./go install golang.org/x/tools/gopls@latest

# Dev tools
./go install golang.org/x/tools/cmd/goimports@latest
./go install mvdan.cc/sh/v3/cmd/shfmt@latest
./go install github.com/xjasonlyu/tun2socks/v2@latest
./go install github.com/antonmedv/countdown@latest
./go install github.com/bootdotdev/bootdev@latest
./go install github.com/sqls-server/sqls@latest
./go install github.com/xo/usql@latest
./go install github.com/charmbracelet/vhs@latest  # terminal recorder
./go install github.com/snowie2000/geoview@0.1.11
./go install github.com/joshmedeski/sesh/v2@latest

# Cursor for opencode
echo "This will run external bash script, do you want to continue? (y/n)"
read -r answer
if [ "$answer" != "${answer#[Yy]}" ]; then
    echo "Continuing..."
else
    echo "Exiting..."
    exit 1
fi
