#!/usr/bin/env bash

# NOTE: check also this tips, there alternative solution: https://userbase.kde.org/Plasma/Tips

# Disabling Win shortcut for Application Launcher
if ! grep -q "ModifierOnlyShortcuts" $HOME/.config/kwinrc ; then
  echo "Disable win key, need logout to apply"
  cat << EOF >> $HOME/.config/kwinrc

[ModifierOnlyShortcuts]
Meta=
EOF
fi
