#!/usr/bin/env bash

sudo apt -y purge neovim kate
sudo apt -y install luarocks

# Install Neovim from nightly release by downloading the precompiled binaries.
backup=true
downloaded_file=/tmp/nvim-linux64.tar.gz
backup_dir=/tmp/nvim-backup

while (( "$#" )); do
  case "$1" in
    --no-backup)
      backup=false
      shift
      ;;
    *)
      echo "Invalid argument: $1"
      exit 1
      ;;
  esac
done

wget2 -O $downloaded_file \
  https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.tar.gz

echo "95aaa8e89473f5421114f2787c13ae0ec6e11ebbd1a13a1bd6fcf63420f8073f  $downloaded_file" \
  | sha256sum -c

# Was the last command ok?
if [ $? -ne 0 ]; then
  echo "Error downloading Neovim"
  exit 1
fi

echo Neovim downloaded

if [ $backup = true ]; then
  echo Backing up old Neovim
  mkdir --parents $backup_dir
  sudo mv /usr/bin/nvim $backup_dir/bin
  sudo mv /usr/lib/nvim $backup_dir/lib
  sudo mv /usr/share/nvim $backup_dir/share
fi

echo Installing Neovim
# --strip-components=1 removes the first directory from the tarball (nvim-linux64).
sudo tar -xzvf $downloaded_file -C /usr/ --strip-components=1
echo Neovim installed!
nvim --version
