#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

#
# Nginx - base install; site configs are linked by app runners (e.g. qbittorrent-nox).

install_packages nginx-light

if [[ "${YADM_IS_WSL:-0}" != "1" ]]; then
    sudo ufw allow http
fi
