#!/usr/bin/env zsh

# Base dependencies
sudo apt install -y nodejs npm shellcheck

npm config set prefix ~/.local/npm

packages=(
    n
    pnpm
    deno
    browser-sync
    single-file-cli
    @biomejs/biome
    @olrtg/emmet-language-server@2.6.1
    bash-language-server
    critical
    typescript-language-server
    typescript
    vscode-langservers-extracted
    dockerfile-language-server-nodejs
    yaml-language-server
    vscode-langservers-extracted
    @google/gemini-cli
    @google/clasp
    @343dev/optimizt
)

for package in "${packages[@]}"; do
    npm install --global "$package"
done

cd "$HOME/.local/npm/bin" || { echo "n binary not found!"; exit 1; }
export N_PREFIX="$HOME/.local/n"
./n lts
./npm config set prefix ~/.local/npm
