#!/usr/bin/env zsh

# Base dependencies
sudo apt install -y nodejs npm shellcheck

sys_npm=/usr/bin/npm

$sys_npm config set prefix ~/.local/npm

packages=(
    n
    pnpm
    deno
    browser-sync
    single-file-cli
    @biomejs/biome
    @olrtg/emmet-language-server
    bash-language-server
    critical
    typescript-language-server
    typescript
    vscode-langservers-extracted
    dockerfile-language-server-nodejs
    yaml-language-server
    vscode-langservers-extracted
    @google/gemini-cli
    @google/clasp
    @343dev/optimizt
    postcss
    postcss-cli
    autoprefixer
)

for package in "${packages[@]}"; do
    $sys_npm install --global "$package"
done

export N_PREFIX="$HOME/.local/n"
export PATH=$N_PREFIX/bin:$PATH

n lts
