#!/bin/sh
cd /tmp || exit 1

# Install LACT
wget2 --progress=bar https://github.com/ilya-zlobintsev/LACT/releases/download/v0.8.0/lact-0.8.0-0.amd64.debian-12.deb
sudo dpkg -i lact-0.8.0-0.amd64.debian-12.deb && rm lact-0.8.0-0.amd64.debian-12.deb
