#!/bin/bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

# Install LACT
VERSION=0.9.0
DEBIAN_VERSION=13
OUT_FILE="/tmp/lact-$VERSION.deb"

download_file \
    "https://github.com/ilya-zlobintsev/LACT/releases/download/v$VERSION/lact-$VERSION-0.amd64.debian-$DEBIAN_VERSION.deb" \
    $OUT_FILE

sudo apt install -y -f $OUT_FILE && rm -f $OUT_FILE
