#!/usr/bin/env bash

set -u

APP_VERSION=1.8.9

APP_NAME=obsidian
APP_DESKTOP_NAME=Obsidian
APP_DESKTOP_DESCRIPTION="A powerful knowledge base that works on top of a local folder of plain text Markdown files"
APP_DESKTOP_CATEGORIES="Development;Education"

APP_PATH="$HOME/.local/bin/$APP_NAME"
TMP_PATH="/tmp/$APP_NAME"
APP_URL="https://github.com/obsidianmd/obsidian-releases/releases/download/v$APP_VERSION/Obsidian-$APP_VERSION.AppImage"
SHA_256_SUM="43dde3caac1c58e9fccbd1ff1a4305b53f784a5ebdef9c59d53851c87c615186"

wget2 --progress=bar --output-document $TMP_PATH $APP_URL
echo "$SHA_256_SUM $TMP_PATH"
echo "$SHA_256_SUM $TMP_PATH" | sha256sum --check || exit 1

mv $TMP_PATH $APP_PATH
chmod a+x $APP_PATH

mkdir -p $HOME/.local/share/applications
cat > "$HOME/.local/share/applications/$APP_NAME.desktop" << EOF
[Desktop Entry]
Version=$APP_VERSION
Name=$APP_DESKTOP_NAME
Comment=$APP_DESKTOP_DESCRIPTION
GenericName=$APP_DESKTOP_NAME
Exec=$HOME/.local/bin/$APP_NAME
Icon=$HOME/.local/bin/icons/$APP_NAME.svg
Terminal=false
Type=Application
Categories=$APP_DESKTOP_CATEGORIES
StartupNotify=true
EOF
