#!/usr/bin/env bash

# TODO: parmetrize!

# libwebkit2gtk-4.0-dev was required for Orca v2.3.0
sudo apt install -y libwebkit2gtk-4.0-dev
wget2 -O $HOME/.local/bin/OrcaSlicer.AppImage
chmod a+x $HOME/.local/bin/OrcaSlicer.AppImage

mkdir -p $HOME/.local/share/applications
cat > $HOME/.local/share/applications/OrcaSlicer.desktop << EOF
[Desktop Entry]
Version=2.3.0
Name=OrcaSlicer
Comment=OrcaSlicer
GenericName=OrcaSlicer
Exec=$HOME/.local/bin/OrcaSlicer.AppImage
Icon=$HOME/.local/bin/icons/OrcaSlicer
Terminal=false
Type=Application
Categories=GTK;Graphics
StartupNotify=true
EOF
