#!/usr/bin/env bash

# TODO: parmetrize!

# libwebkit2gtk-4.1-dev was required for Orca v2.3.0+
sudo apt install -y libwebkit2gtk-4.1-dev
URL="https://github.com/SoftFever/OrcaSlicer/releases/download/nightly-builds/OrcaSlicer_Linux_AppImage_Ubuntu2404_nightly.AppImage"
wget2 --progress=bar --output-document $HOME/.local/bin/OrcaSlicer.AppImage $URL
chmod a+x $HOME/.local/bin/OrcaSlicer.AppImage

mkdir -p $HOME/.local/share/applications
cat > $HOME/.local/share/applications/OrcaSlicer.desktop << EOF
[Desktop Entry]
Version=2.3.0
Name=OrcaSlicer
Comment=OrcaSlicer
GenericName=OrcaSlicer
Exec=$HOME/.local/bin/OrcaSlicer.AppImage
Icon=$HOME/.local/bin/icons/OrcaSlicer
Terminal=false
Type=Application
Categories=GTK;Graphics
StartupNotify=true
EOF
