#!/usr/bin/env bash

# Global Python
sudo apt install -y python3-full

# Get uv
if ! command -v uv &> /dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
else
    uv self update
fi

cd "$HOME/.local/bin" || {
    echo "Error: Failed to change directory to $HOME/.local/bin" >&2
    exit 1
}

# Install tools
for tool in ruff basedpyright debugpy "python-lsp-server --with pylsp-rope" mypy ipython pipdeptree sqlfluff djlint llm obs-cli files-to-prompt tmuxp; do
    ./uv tool install --upgrade $tool
done

# Install tools without upgrading
for tool in argostranslate piper-tts; do
    ./uv tool install $tool
done

./uv tool run llm install llm-openrouter llm-ollama
