#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

# Global Python
sudo apt install -y python3-full python3-aiohttp python3-debugpy patchelf

# Xdot
sudo apt install -y xdot

# Get uv
if ! command -v uv &>/dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
else
    uv self update
fi

cd "$HOME/.local/bin" || {
    echo "Error: Failed to change directory to $HOME/.local/bin" >&2
    exit 1
}

# Install tools
for tool in ruff \
            basedpyright \
            "python-lsp-server --with pylsp-rope" \
            copier \
            mypy \
            ipython \
            pipdeptree \
            sqlfluff \
            djlint \
            pylint \
            llm \
            obs-cli \
            "DSLR --with psycopg2-binary" \
            "markitdown[pdf, docx, pptx]" \
            files-to-prompt \
            mistral-vibe \
            nuitka; do
    ./uv tool install --upgrade $tool
done

# Install tools without upgrading
for tool in argostranslate piper-tts; do
    ./uv tool install $tool
done

./uv tool run llm install \
    llm-openrouter \
    llm-ollama \
    llm-gemini \
    llm-mistral
