#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install build-essential gcc unzip wget zip avrdude gcc-avr binutils-avr\
    avr-libc dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi\
    libnewlib-arm-none-eabi git
