#!/bin/bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

# --- Anydesk
#
# Add the AnyDesk GPG key
sudo apt update
sudo apt install ca-certificates curl apt-transport-https
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://keys.anydesk.com/repos/DEB-GPG-KEY -o /etc/apt/keyrings/keys.anydesk.com.asc
sudo chmod a+r /etc/apt/keyrings/keys.anydesk.com.asc

# Add the AnyDesk apt repository
echo "deb [signed-by=/etc/apt/keyrings/keys.anydesk.com.asc] https://deb.anydesk.com all main" | sudo tee /etc/apt/sources.list.d/anydesk-stable.list > /dev/null

# Update apt caches and install the AnyDesk client
sudo apt update
sudo apt install anydesk
sudo systemctl mask anydesk
sudo rm -f /etc/xdg/autostart/anydesk_global_tray.desktop
sudo dpkg-divert --add --rename --divert /etc/systemd/system/anydesk.service.unused /etc/systemd/system/anydesk.service

# --- Remmina
#
sudo apt install -y remmina
