#!/usr/bin/env bash

echo "deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free" | sudo tee /etc/apt/sources.list.d/resilio-sync.list
wget -qO- https://linux-packages.resilio.com/resilio-sync/key.asc | sudo tee /etc/apt/trusted.gpg.d/resilio-sync.asc > /dev/null 2>&1
sudo apt-get update
sudo apt-get install resilio-sync
sudo systemctl disable resilio-sync
sudo systemctl stop resilio-sync

# Fix /usr/lib/systemd/user/resilio-sync.service
sudo sed -i 's/WantedBy=multi-user.target/WantedBy=default.target/w /dev/stdout' /usr/lib/systemd/user/resilio-sync.service|grep -q .
if test $? = 0; then
    echo "Updated resilio systemd service file";
else
    echo "Nothing updated, assuming service file was already corrected. OR SOME ISSUE DETECTED";
fi;

systemctl --user daemon-reload
systemctl --user enable --now resilio-sync

# Check status
echo "Checking Resilio Sync service status:"
