#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

check_not_root
check_home_set

install_packages \
    git \
    build-essential \
    meson \
    ninja-build \
    pkg-config \
    flex \
    bison \
    check \
    libpango1.0-dev \
    libcairo2-dev \
    libglib2.0-dev \
    libgdk-pixbuf-2.0-dev \
    libstartup-notification0-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    libxcb1-dev \
    libxcb-xkb-dev \
    libxcb-randr0-dev \
    libxcb-xinerama0-dev \
    libxcb-util-dev \
    libxcb-ewmh-dev \
    libxcb-icccm4-dev \
    libxcb-cursor-dev \
    libxcb-keysyms1-dev \
    libwayland-dev \
    wayland-protocols \
    qalc

SRC_DIR="$HOME/Desktop/software/rofi"
BUILD_DIR="$SRC_DIR/build"

if [[ -d "$SRC_DIR/.git" ]]; then
    log_info "Updating rofi checkout"
    git -C "$SRC_DIR" pull
    git -C "$SRC_DIR" submodule update --init --recursive
else
    log_info "Cloning rofi checkout"
    mkdir -p "$(dirname "$SRC_DIR")"
    git clone --recursive https://github.com/davatorium/rofi.git "$SRC_DIR"
fi

cd_or_exit "$SRC_DIR"

if [[ -f "$BUILD_DIR/build.ninja" ]]; then
    meson setup "$BUILD_DIR" --reconfigure --prefix "$HOME/.local"
else
    meson setup "$BUILD_DIR" --prefix "$HOME/.local"
fi

ninja -C "$BUILD_DIR"
ninja -C "$BUILD_DIR" install

# rofi-calc: use the rofi we just installed (not distro rofi-dev)
if [[ -d "$HOME/.local/lib/x86_64-linux-gnu/pkgconfig" ]]; then
    export PKG_CONFIG_PATH="$HOME/.local/lib/x86_64-linux-gnu/pkgconfig:$HOME/.local/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
else
    export PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
fi

# ROFI calc
# =========
CALC_SRC_DIR="$HOME/Desktop/software/rofi-calc"
CALC_BUILD_DIR="$CALC_SRC_DIR/build"

if [[ -d "$CALC_SRC_DIR/.git" ]]; then
    log_info "Updating rofi-calc checkout"
    git -C "$CALC_SRC_DIR" pull
else
    log_info "Cloning rofi-calc checkout"
    mkdir -p "$(dirname "$CALC_SRC_DIR")"
    git clone https://github.com/svenstaro/rofi-calc.git "$CALC_SRC_DIR"
fi

cd_or_exit "$CALC_SRC_DIR"

if [[ -f "$CALC_BUILD_DIR/build.ninja" ]]; then
    meson setup "$CALC_BUILD_DIR" --reconfigure --prefix "$HOME/.local"
else
    meson setup "$CALC_BUILD_DIR" --prefix "$HOME/.local"
fi

ninja -C "$CALC_BUILD_DIR"
ninja -C "$CALC_BUILD_DIR" install
