#!/bin/sh

PKGURL="https://downloads.slack-edge.com/desktop-releases/linux/x64/4.43.51/slack-desktop-4.43.51-amd64.deb"
cd /tmp || exit 1
wget2 --progress=bar --output-document slack.deb $PKGURL
sudo dpkg -i ./slack.deb
rm ./slack.deb
