#!/usr/bin/env bash
set -e

sudo apt remove -y tmux
sudo apt install -y libevent-dev ncurses-dev build-essential bison pkg-config

pkgname=tmux
pkgver=3.5_a
pkgrel=1
pkgdesc='Terminal multiplexer'
url='https://github.com/tmux/tmux/wiki'
arch=('x86_64')
license=('BSD')
depends=('libevent' 'libevent_core-2.1.so'
         'libutempter'
         'ncurses' 'libncursesw.so'
         'systemd-libs' 'libsystemd.so')
makedepends=('git' 'systemd')
source=("git+https://github.com/tmux/tmux.git#tag=${pkgver/_/}")
sha256sums=('4809a5c8289027f4bc15a06bd232f5797d7dd9ba47adf4c3135c5295aece6ff5')

MYTMPDIR="$(mktemp -d)"
trap 'rm -rf -- "$MYTMPDIR"' EXIT
cd $MYTMPDIR

prepare() {
	git clone --depth=1 https://github.com/tmux/tmux.git . || echo "Seems tmux already cloned!"
	sh autogen.sh
}

build() {
	./configure \
		--prefix=$HOME/.local \
		--enable-sixel
	make && make install && rm -rf "/tmp/$pkgname"
}

prepare
build
