#!/usr/bin/env bash

curl -LsSf https://astral.sh/uv/install.sh | sh

# Install some tools
for tool in ruff basedpyright debugpy mypy ipython pipdeptree; do
    $HOME/.local/bin/uv tool install --upgrade $tool
done
