#!/usr/bin/env bash

source "$(dirname -- "${BASH_SOURCE[0]}")/utils.sh"

install_packages dkms "linux-headers-$(uname -r)"

git clone https://github.com/dlundqvist/xone /tmp/xone
cd_or_exit /tmp/xone
sudo ./install.sh
sudo ./install/firmware.sh
rm -rf /tmp/xone
