#!/usr/bin/env bash

sudo apt update
sudo apt install zathura zathura-cb mupdf texlive-base texlive
sudo apt install libmupdf-dev zathura-dev gcc meson ca-certificates binutils
mkdir -p /tmp/zathura
cd /tmp/zathura || exit 1
git clone https://github.com/pwmt/zathura-pdf-mupdf zathura-develop
cd zathura-develop || exit 1
meson build
cd build || exit 1
ninja
ninja install
