#!/usr/bin/env bash

sudo apt install zsh
hash -r
sudo chsh -s $(which zsh)
# git clone --recursive https://github.com/changs/slimzsh.git ~/.slimzsh
# source "$HOME/.slimzsh/slim.zsh"
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

